# This is a basic workflow to help you get started with Actions

name: Refresh region service map file

on:
  schedule:
    - cron: "0 9 * * *" #runs at 09:00 UTC everyday
  workflow_dispatch:

env:
  GITHUB_BRANCH: "main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl https://api.regional-table.region-services.aws.a2z.com/index.json -o pkg/awsservicemap/data/aws-service-regions.json

      # Create pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update aws service region map file."
          branch: "aws-services-regions-updated"
          labels: "status/waiting-for-revision, severity/low"
          title: "Updating the aws service region map file."
          body: |
            ### Description

            This PR updates the aws service region map file.
